"""Record which pages of a CV are laid out in columns.

Revision ID: 460eadf66231
Revises: f2a4b8d6c135

Extraction flattens a page into one stream of lines, and for a two-column CV
that stream interleaves two unrelated narratives. On one real CV it placed an
education line from the left column after the experience heading from the
right, and the screener counted a school stream as a job -- 58 months of
"professional experience" out of about 14.

The column geometry is only visible while the PDF is open, so it has to be
stored rather than derived later from the text. `parsed_document` already keeps
`injection_flags` this way, for the same reason and to the same end: the
recruiter is told what the reader could not be sure of, instead of being shown a
confident wrong answer.

Autogenerated, then rewritten in this repository's style. One nullable JSONB
column, so every existing row stays valid with no backfill: an older parse
simply has no opinion about its layout, which is true.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "460eadf66231"
down_revision = "f2a4b8d6c135"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "parsed_document",
        sa.Column("multi_column_pages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("parsed_document", "multi_column_pages")
