"""initial schema

Revision ID: b527c519d55f
Revises: 
Create Date: 2026-09-06 22:05:12.896090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b527c519d55f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --------------------------------------------------------------------------
# Hand-corrected after autogenerate. Alembic rendered each enum as
# `sa.Enum(..., metadata=MetaData())`, which was wrong three ways:
#
#   1. `MetaData` is not imported in this file, so the module would not even
#      import.
#   2. requirement_category, match_verdict and recommendation_band are each
#      used by two columns. Rendered as separate objects they would emit
#      CREATE TYPE twice and PostgreSQL rejects the duplicate.
#   3. DROP TABLE does not drop a PostgreSQL enum type, so the generated
#      downgrade left all 14 types behind and a downgrade/upgrade cycle
#      failed on the second run.
#
# Each type is therefore declared once, created explicitly before the tables
# and dropped explicitly after them.
# --------------------------------------------------------------------------

enum_candidate_status = postgresql.ENUM(
    'UPLOADED', 'PARSING', 'PARSED', 'EXTRACTING', 'EXTRACTED', 'SCORING', 'SCORED', 'FAILED',
    name="candidate_status",
    create_type=False,
)
enum_candidate_failure_reason = postgresql.ENUM(
    'CORRUPT_FILE', 'NO_TEXT_LAYER', 'UNSUPPORTED_LANGUAGE', 'PARSE_TIMEOUT', 'EXTRACTION_FAILED', 'MATCHING_FAILED',
    name="candidate_failure_reason",
    create_type=False,
)
enum_jd_source_type = postgresql.ENUM(
    'PASTED', 'UPLOADED',
    name="jd_source_type",
    create_type=False,
)
enum_llm_purpose = postgresql.ENUM(
    'JD_EXTRACTION', 'PROFILE_EXTRACTION', 'SEMANTIC_MATCH',
    name="llm_purpose",
    create_type=False,
)
enum_llm_source = postgresql.ENUM(
    'LIVE', 'FIXTURE',
    name="llm_source",
    create_type=False,
)
enum_llm_status = postgresql.ENUM(
    'SUCCESS', 'SCHEMA_INVALID', 'PROVIDER_ERROR', 'TIMEOUT',
    name="llm_status",
    create_type=False,
)
enum_requirement_category = postgresql.ENUM(
    'EDUCATION', 'TECHNICAL_SKILL', 'EXPERIENCE', 'PROJECT', 'SOFT_SKILL_OTHER',
    name="requirement_category",
    create_type=False,
)
enum_requirement_origin = postgresql.ENUM(
    'LLM_EXTRACTED', 'HR_ADDED',
    name="requirement_origin",
    create_type=False,
)
enum_evidence_verification = postgresql.ENUM(
    'VERIFIED_EXACT', 'VERIFIED_NORMALIZED', 'UNVERIFIED',
    name="evidence_verification",
    create_type=False,
)
enum_score_status = postgresql.ENUM(
    'COMPUTED', 'UNDEFINED_NO_WEIGHT',
    name="score_status",
    create_type=False,
)
enum_recommendation_band = postgresql.ENUM(
    'STRONG_MATCH', 'GOOD_MATCH', 'REVIEW', 'LOW_MATCH',
    name="recommendation_band",
    create_type=False,
)
enum_match_verdict = postgresql.ENUM(
    'MATCHED', 'PARTIAL', 'NO_EVIDENCE',
    name="match_verdict",
    create_type=False,
)
enum_match_method = postgresql.ENUM(
    'DETERMINISTIC_EXACT', 'DETERMINISTIC_ALIAS', 'DETERMINISTIC_DURATION', 'LLM_SEMANTIC', 'DOWNGRADED_UNVERIFIED',
    name="match_method",
    create_type=False,
)
enum_date_precision = postgresql.ENUM(
    'DAY', 'MONTH', 'YEAR', 'UNKNOWN',
    name="date_precision",
    create_type=False,
)

ENUM_TYPES = (
    enum_candidate_status,
    enum_candidate_failure_reason,
    enum_jd_source_type,
    enum_llm_purpose,
    enum_llm_source,
    enum_llm_status,
    enum_requirement_category,
    enum_requirement_origin,
    enum_evidence_verification,
    enum_score_status,
    enum_recommendation_band,
    enum_match_verdict,
    enum_match_method,
    enum_date_precision,
)



def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum_type in ENUM_TYPES:
        enum_type.create(bind, checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('requirements_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(title) BETWEEN 1 AND 200', name=op.f('ck_job_title_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('ix_job_created_at', 'job', ['created_at'], unique=False)
    op.create_table('skill_alias',
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_alias')),
    sa.UniqueConstraint('alias', name='uq_skill_alias_alias')
    )
    op.create_table('candidate',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('status', enum_candidate_status, nullable=False),
    sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', enum_candidate_failure_reason, nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'FAILED') = (failure_reason IS NOT NULL)", name=op.f('ck_candidate_failure_reason_iff_failed')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_candidate_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate'))
    )
    op.create_index('ix_candidate_job_id_status', 'candidate', ['job_id', 'status'], unique=False)
    op.create_table('job_description',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_type', enum_jd_source_type, nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(raw_text) BETWEEN 1 AND 100000', name=op.f('ck_job_description_raw_text_length')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_description_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_description')),
    sa.UniqueConstraint('job_id', name=op.f('uq_job_description_job_id'))
    )
    op.create_table('candidate_document',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_candidate_document_size_positive')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_candidate_document_candidate_id_candidate'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_document')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_candidate_document_candidate_id'))
    )
    op.create_index('ix_candidate_document_file_sha256', 'candidate_document', ['file_sha256'], unique=False)
    op.create_table('llm_call_log',
    sa.Column('purpose', enum_llm_purpose, nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('source', enum_llm_source, nullable=False),
    sa.Column('status', enum_llm_status, nullable=False),
    sa.Column('attempt', sa.SmallInteger(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('raw_response_excerpt', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_llm_call_log_candidate_id_candidate'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_llm_call_log_job_id_job'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call_log'))
    )
    op.create_index('ix_llm_call_log_created_at', 'llm_call_log', ['created_at'], unique=False)
    op.create_index('ix_llm_call_log_input_sha256_prompt_version_model', 'llm_call_log', ['input_sha256', 'prompt_version', 'model'], unique=False)
    op.create_table('parsed_document',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('normalization_version', sa.Text(), nullable=False),
    sa.Column('page_offsets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('language_detected', sa.Text(), nullable=True),
    sa.Column('injection_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('parser_name', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_document.id'], name=op.f('fk_parsed_document_document_id_candidate_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parsed_document')),
    sa.UniqueConstraint('document_id', name=op.f('uq_parsed_document_document_id'))
    )
    op.create_index('ix_parsed_document_text_sha256', 'parsed_document', ['text_sha256'], unique=False)
    op.create_table('requirement',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', enum_requirement_category, nullable=False),
    sa.Column('must_have', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('origin', enum_requirement_origin, nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('proposed_category', enum_requirement_category, nullable=True),
    sa.Column('proposed_must_have', sa.Boolean(), nullable=True),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_requirement_weight_non_negative')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_requirement_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call_log.id'], name=op.f('fk_requirement_llm_call_id_llm_call_log'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement'))
    )
    op.create_index('ix_requirement_job_id_display_order', 'requirement', ['job_id', 'display_order'], unique=False)
    op.create_table('candidate_profile',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_candidate_profile_candidate_id_candidate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call_log.id'], name=op.f('fk_candidate_profile_llm_call_id_llm_call_log'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_document.id'], name=op.f('fk_candidate_profile_parsed_document_id_parsed_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profile')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_candidate_profile_candidate_id'))
    )
    op.create_table('evidence_span',
    sa.Column('parsed_document_id', sa.UUID(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('verification_status', enum_evidence_verification, nullable=False),
    sa.Column('normalization_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verification_status = 'UNVERIFIED') = (start_char IS NULL)", name=op.f('ck_evidence_span_located_iff_verified')),
    sa.ForeignKeyConstraint(['parsed_document_id'], ['parsed_document.id'], name=op.f('fk_evidence_span_parsed_document_id_parsed_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_span'))
    )
    op.create_index('ix_evidence_span_parsed_document_id', 'evidence_span', ['parsed_document_id'], unique=False)
    op.create_table('score',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', enum_score_status, nullable=False),
    sa.Column('weighted_sum', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_raw', sa.Numeric(precision=9, scale=8), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('must_have_coverage', sa.Numeric(precision=9, scale=8), nullable=True),
    sa.Column('band_raw', enum_recommendation_band, nullable=True),
    sa.Column('band', enum_recommendation_band, nullable=True),
    sa.Column('capped', sa.Boolean(), nullable=False),
    sa.Column('capped_by_requirement_id', sa.UUID(), nullable=True),
    sa.Column('scoring_config_version', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_score_score_range')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_score_candidate_id_candidate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['capped_by_requirement_id'], ['requirement.id'], name=op.f('fk_score_capped_by_requirement_id_requirement'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score')),
    sa.UniqueConstraint('candidate_id', name=op.f('uq_score_candidate_id'))
    )
    op.create_table('match_result',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('verdict', enum_match_verdict, nullable=False),
    sa.Column('decided_by', enum_match_method, nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_span_id', sa.UUID(), nullable=True),
    sa.Column('raw_verdict', enum_match_verdict, nullable=True),
    sa.Column('downgraded', sa.Boolean(), nullable=False),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict = 'NO_EVIDENCE' OR evidence_span_id IS NOT NULL", name=op.f('ck_match_result_positive_verdict_requires_evidence')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('fk_match_result_candidate_id_candidate'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], name=op.f('fk_match_result_evidence_span_id_evidence_span'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call_log.id'], name=op.f('fk_match_result_llm_call_id_llm_call_log'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_match_result_requirement_id_requirement'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_result')),
    sa.UniqueConstraint('requirement_id', 'candidate_id', name='uq_match_result_requirement_candidate')
    )
    op.create_index('ix_match_result_candidate_id', 'match_result', ['candidate_id'], unique=False)
    op.create_table('profile_education',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('completion_year', sa.Integer(), nullable=True),
    sa.Column('evidence_span_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], name=op.f('fk_profile_education_evidence_span_id_evidence_span'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.id'], name=op.f('fk_profile_education_profile_id_candidate_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_education'))
    )
    op.create_index('ix_profile_education_profile_id', 'profile_education', ['profile_id'], unique=False)
    op.create_table('profile_experience',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('role_title', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('date_precision', enum_date_precision, nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_span_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], name=op.f('fk_profile_experience_evidence_span_id_evidence_span'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.id'], name=op.f('fk_profile_experience_profile_id_candidate_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_experience'))
    )
    op.create_index('ix_profile_experience_profile_id', 'profile_experience', ['profile_id'], unique=False)
    op.create_table('profile_project',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('evidence_span_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], name=op.f('fk_profile_project_evidence_span_id_evidence_span'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.id'], name=op.f('fk_profile_project_profile_id_candidate_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_project'))
    )
    op.create_index('ix_profile_project_profile_id', 'profile_project', ['profile_id'], unique=False)
    op.create_table('profile_skill',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('evidence_span_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_span.id'], name=op.f('fk_profile_skill_evidence_span_id_evidence_span'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profile.id'], name=op.f('fk_profile_skill_profile_id_candidate_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_skill'))
    )
    op.create_index('ix_profile_skill_profile_id_normalized_name', 'profile_skill', ['profile_id', 'normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_skill_profile_id_normalized_name', table_name='profile_skill')
    op.drop_table('profile_skill')
    op.drop_index('ix_profile_project_profile_id', table_name='profile_project')
    op.drop_table('profile_project')
    op.drop_index('ix_profile_experience_profile_id', table_name='profile_experience')
    op.drop_table('profile_experience')
    op.drop_index('ix_profile_education_profile_id', table_name='profile_education')
    op.drop_table('profile_education')
    op.drop_index('ix_match_result_candidate_id', table_name='match_result')
    op.drop_table('match_result')
    op.drop_table('score')
    op.drop_index('ix_evidence_span_parsed_document_id', table_name='evidence_span')
    op.drop_table('evidence_span')
    op.drop_table('candidate_profile')
    op.drop_index('ix_requirement_job_id_display_order', table_name='requirement')
    op.drop_table('requirement')
    op.drop_index('ix_parsed_document_text_sha256', table_name='parsed_document')
    op.drop_table('parsed_document')
    op.drop_index('ix_llm_call_log_input_sha256_prompt_version_model', table_name='llm_call_log')
    op.drop_index('ix_llm_call_log_created_at', table_name='llm_call_log')
    op.drop_table('llm_call_log')
    op.drop_index('ix_candidate_document_file_sha256', table_name='candidate_document')
    op.drop_table('candidate_document')
    op.drop_table('job_description')
    op.drop_index('ix_candidate_job_id_status', table_name='candidate')
    op.drop_table('candidate')
    op.drop_table('skill_alias')
    op.drop_index('ix_job_created_at', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###

    # Tables are gone; the enum types they used are not. Drop them too, or a
    # subsequent upgrade fails with 'type already exists'.
    bind = op.get_bind()
    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(bind, checkfirst=False)
