"""Structured screening criteria and the NEEDS_REVIEW verdict (ADR-0012).

Revision ID: d4e81c30ab97
Revises: c1a7f3b90e42

Written by hand rather than autogenerated. `alembic check` reports no drift for
either change below: it does not compare the *values* of a PostgreSQL enum
against the Python enum, and it does not see a CHECK constraint expressed as
text. Relying on autogenerate here would have shipped a schema in which writing
a NEEDS_REVIEW verdict fails at runtime.

Two changes:

1. **Three new enum values.** `match_verdict` gains NEEDS_REVIEW,
   `score_status` gains UNDEFINED_NO_DECIDABLE, and `match_method` gains
   DETERMINISTIC_STRUCTURED so the audit trail can say which engine decided.

2. **Structured requirement columns.** A requirement written by the criteria
   builder carries its type and values; a legacy free-text requirement carries
   none of them. A CHECK constraint enforces that a row is wholly one or wholly
   the other, so there is no half-structured state for the matcher to guess at.

On `ALTER TYPE ... ADD VALUE` inside a transaction: PostgreSQL 12 and later
allow it, provided the new value is not *used* in the same transaction. Nothing
here writes one, so the migration runs in Alembic's normal transaction.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "d4e81c30ab97"
down_revision = "c1a7f3b90e42"
branch_labels = None
depends_on = None


#: The six criterion types of ADR-0012. Deliberately a closed set in the
#: database as well as in the application: an unsupported criterion should be
#: impossible to store, not merely impossible to evaluate.
SPEC_TYPES = (
    "EDUCATION_MIN",
    "GPA_MIN",
    "EXPERIENCE_MIN",
    "SKILL",
    "INTERNSHIP_MIN",
    "LANGUAGE_PRESENT",
)

#: A row is either fully structured or fully legacy.
#:
#: * no `spec_type` -> every structured column is NULL (free-text, pre-ADR-0012)
#: * a `spec_type` that names a thing -> `subject` is required
#: * a `spec_type` that sets a bar    -> `threshold_value` is required, except
#:   INTERNSHIP_MIN, where presence alone is a legitimate criterion
#: * `threshold_scale` belongs to GPA_MIN and to nothing else
#:
#: Written as CASE rather than as a chain of ORs on purpose. `spec_type IN (...)`
#: evaluates to NULL when `spec_type` is NULL, and PostgreSQL **accepts** a CHECK
#: whose expression is NULL -- so the OR form silently let through exactly the
#: half-structured row it was meant to stop (subject set, no type to interpret
#: it). CASE makes the NULL branch explicit and the ELSE arm total.
_VALID_SPEC = """
CASE
    WHEN spec_type IS NULL THEN
        subject IS NULL AND threshold_value IS NULL AND threshold_scale IS NULL
    WHEN spec_type IN ('EDUCATION_MIN', 'SKILL', 'LANGUAGE_PRESENT') THEN
        subject IS NOT NULL AND threshold_value IS NULL AND threshold_scale IS NULL
    WHEN spec_type = 'GPA_MIN' THEN
        subject IS NULL AND threshold_value IS NOT NULL
    WHEN spec_type = 'EXPERIENCE_MIN' THEN
        subject IS NULL AND threshold_value IS NOT NULL AND threshold_scale IS NULL
    WHEN spec_type = 'INTERNSHIP_MIN' THEN
        subject IS NULL AND threshold_scale IS NULL
    ELSE FALSE
END
"""


def upgrade() -> None:
    # 1. New verdict and score status ------------------------------------
    op.execute("ALTER TYPE match_verdict ADD VALUE IF NOT EXISTS 'NEEDS_REVIEW'")
    op.execute("ALTER TYPE score_status ADD VALUE IF NOT EXISTS 'UNDEFINED_NO_DECIDABLE'")
    op.execute(
        "ALTER TYPE match_method ADD VALUE IF NOT EXISTS 'DETERMINISTIC_STRUCTURED'"
    )

    # 2. Structured requirement columns ----------------------------------
    spec_type = postgresql.ENUM(*SPEC_TYPES, name="requirement_spec_type", create_type=False)
    spec_type.create(op.get_bind(), checkfirst=True)

    op.add_column("requirement", sa.Column("spec_type", spec_type, nullable=True))
    op.add_column("requirement", sa.Column("subject", sa.Text(), nullable=True))
    op.add_column("requirement", sa.Column("threshold_value", sa.Numeric(6, 2), nullable=True))
    op.add_column("requirement", sa.Column("threshold_scale", sa.Numeric(4, 2), nullable=True))

    op.create_check_constraint("spec_is_complete", "requirement", _VALID_SPEC)
    op.create_check_constraint(
        "threshold_non_negative",
        "requirement",
        "threshold_value IS NULL OR threshold_value >= 0",
    )
    op.create_check_constraint(
        "scale_positive",
        "requirement",
        "threshold_scale IS NULL OR threshold_scale > 0",
    )

    # 3. Let the evidence rule admit the fourth verdict ------------------
    # The existing constraint reads "verdict = 'NO_EVIDENCE' OR a span exists",
    # which is a closed enumeration over the three original verdicts: a
    # NEEDS_REVIEW row without a span fails it, so every structured screening
    # run would have died at the point of saving an unresolved criterion.
    # NEEDS_REVIEW joins the exemption because it makes no claim about the
    # candidate and legitimately arrives both with a span (a grade whose scale
    # is missing) and without one (a skill outside the vocabulary).
    #
    # The comparison is written against `verdict::text` rather than against the
    # enum. PostgreSQL refuses to *use* an enum value added earlier in the same
    # transaction ("unsafe use of new value ... must be committed first"), and
    # naming 'NEEDS_REVIEW' as an enum literal here counts as using it. Casting
    # to text compares the label instead, which is legal in the same
    # transaction and keeps this a single migration.
    op.drop_constraint("positive_verdict_requires_evidence", "match_result", type_="check")
    op.create_check_constraint(
        "positive_verdict_requires_evidence",
        "match_result",
        "verdict::text IN ('NO_EVIDENCE', 'NEEDS_REVIEW') OR evidence_span_id IS NOT NULL",
    )


def downgrade() -> None:
    # Restore the three-verdict evidence rule. Safe in this direction only
    # because a downgrade also removes the ability to produce NEEDS_REVIEW.
    op.drop_constraint(
        "positive_verdict_requires_evidence", "match_result", type_="check"
    )
    op.create_check_constraint(
        "positive_verdict_requires_evidence",
        "match_result",
        "verdict = 'NO_EVIDENCE' OR evidence_span_id IS NOT NULL",
    )

    op.drop_constraint("scale_positive", "requirement", type_="check")
    op.drop_constraint("threshold_non_negative", "requirement", type_="check")
    op.drop_constraint("spec_is_complete", "requirement", type_="check")

    op.drop_column("requirement", "threshold_scale")
    op.drop_column("requirement", "threshold_value")
    op.drop_column("requirement", "subject")
    op.drop_column("requirement", "spec_type")

    op.execute("DROP TYPE IF EXISTS requirement_spec_type")

    # The two enum VALUES added above are not removed: PostgreSQL has no
    # `ALTER TYPE ... DROP VALUE`, and rebuilding `match_verdict` would mean
    # rewriting every `match_result` row to do it. Leaving an unused label on an
    # enum is harmless, and a downgrade all the way to base drops both types
    # outright, so the round trip CI exercises still returns a clean schema.
