"""Local filesystem storage for uploaded documents.

Uploaded files are untrusted, and the filename is the least trustworthy part of
them. The rule this module exists to enforce: **a client-supplied name never
influences where a byte lands on disk.** The stored path is derived entirely
from a server-generated UUID; the original filename survives only as display
metadata on the row.

Deliberately a plain directory. docs/architecture.md section 13 lists object
storage as out of scope, and the demo runs on synthetic CVs; a local directory
is the honest MVP choice. The interface is narrow enough that swapping in
object storage later touches this file and nothing else.
"""

from __future__ import annotations

import uuid
from pathlib import Path

#: Every stored document is a PDF; Phase 5 accepts no other format.
_SUFFIX = ".pdf"


class StoragePathError(RuntimeError):
    """A stored path resolved outside the storage root.

    Paths are generated by this module, so reaching this means a stored value
    was tampered with or a bug produced one. Either way, reading the file would
    be reading somewhere it should not.
    """


class DocumentStorage:
    """Reads and writes document bytes under a single root directory."""

    def __init__(self, root: Path) -> None:
        self._root = Path(root).resolve()

    @property
    def root(self) -> Path:
        return self._root

    def build_relative_path(self, document_id: uuid.UUID) -> str:
        """Derive the storage path from the document id, and nothing else.

        Sharded on the first two hex characters so one directory does not
        accumulate every document ever uploaded. Always POSIX-style separators,
        so a path written on Windows resolves on Linux and vice versa.
        """
        stem = document_id.hex
        return f"{stem[:2]}/{stem}{_SUFFIX}"

    def resolve(self, relative_path: str) -> Path:
        """Turn a stored relative path into an absolute one, safely.

        Guards against traversal even though this module generates the paths
        itself: the check costs nothing and means a tampered database value
        cannot make the application read outside its own storage.
        """
        candidate = (self._root / relative_path).resolve()
        if candidate != self._root and self._root not in candidate.parents:
            raise StoragePathError("Resolved storage path escapes the storage root.")
        return candidate

    def save(self, document_id: uuid.UUID, data: bytes) -> str:
        """Write `data` and return the relative path to store on the row.

        A **relative** path is returned on purpose: the database should not
        record the server's filesystem layout, and the storage root can move
        between environments without a data migration.
        """
        relative_path = self.build_relative_path(document_id)
        destination = self.resolve(relative_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        return relative_path

    def read(self, relative_path: str) -> bytes:
        return self.resolve(relative_path).read_bytes()

    def exists(self, relative_path: str) -> bool:
        return self.resolve(relative_path).is_file()

    def delete(self, relative_path: str) -> None:
        """Remove a stored file. Missing is not an error — deletion is the goal."""
        self.resolve(relative_path).unlink(missing_ok=True)
